config/routes.rb
Rails.application.routes.draw do
  root 'pokemon_cards#index'
  resources :pokemon_cards, only: [:index, :show]
  resources :types, only: [:show]

  resources :search, only: [:index]
  resources :abouts, only: [:index]
  resources :contacts, only: [:index]

  resources :cart, only: [:index, :create, :update, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :customers
  scope '/customers' do
    resources :orders, only: [:index, :show, :new, :create] do
      get 'edit_shipping_address', on: :collection
      post 'update_shipping_address', on: :collection
    end
  end

  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/about.rb
class About < ApplicationRecord
    validates :content, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :title, presence: true
    validates :email, presence: true, format: { with: /\A\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+\z/, message: "is invalid" }
    validates :phone, presence: true, format: { with: /\A[\+]?\d{0,3}[(]?\d{3}[)]?[-\s\.]?\d{3}[-\s\.]?\d{4}\z/, message: "is invalid" }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province, optional: true

  has_many :orders

  validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9_-]{3,15}\z/, message: "should be 3 to 15 characters long and can only contain letters, digits, underscores, and hyphens" }
  validates :email, format: { with: /\A\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+\z/, message: "is invalid" }
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    belongs_to :province

    has_many :order_details

    validates :customer_id, presence: true
    validates :province_id, presence: true
    validates :address, presence: true

    def total_quantity
        order_details.sum { |item| item.quantity }
    end

    def subtotal
        order_details.sum { |item| item.quantity * item.price }
    end

    def tax_history
        province.tax_histories.where("created_at <= ?", created_at).order(created_at: :desc).first
    end

    def pst
        subtotal * (tax_history&.pst || 0) / 100
    end

    def gst
        subtotal * (tax_history&.gst || 0) / 100
    end

    def hst
        subtotal * (tax_history&.hst || 0) / 100
    end

    def total
        subtotal + pst + gst + hst
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :pokemon_card

    validates :order_id, presence: true
    validates :pokemon_card_id, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0.01 }
    validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/pokemon_card.rb
class PokemonCard < ApplicationRecord
    has_and_belongs_to_many :types
    has_many :price_histories
    has_many :order_details

    has_one_attached :image

    validates :name, presence: true
    validates :stock_quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }

    validate :image_presence
    validate :types_presence

    def new?
        created_at >= 3.days.ago
    end

    def recently_updated?
        updated_at >= 3.days.ago
    end

    def price
        price_histories.order(created_at: :desc).first.price
    end

    private

    def image_presence
        errors.add(:image, "must be attached") unless image.attached?
    end

    def types_presence
        errors.add(:types, "must be present") if types.empty?
    end
end

app/models/price_history.rb
class PriceHistory < ApplicationRecord
    belongs_to :pokemon_card

    validates :pokemon_card_id, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0.01 }
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :tax_histories
    has_many :customers
    has_many :orders

    validates :name, presence: true, uniqueness: true
end

app/models/tax_history.rb
class TaxHistory < ApplicationRecord
    belongs_to :province

    validates :province_id, presence: true
    validates :pst, :gst, :hst, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }, allow_nil: true
    validate :at_least_one_tax_present_and_positive

    private

    def at_least_one_tax_present_and_positive
        if [pst, gst, hst].all?(&:blank?)
            errors.add(:base, "at least one tax must be present")
        elsif [pst, gst, hst].none? { |tax| tax.to_f > 0 }
            errors.add(:base, "at least one tax must be greater than 0")
        end
    end
end

app/models/type.rb
class Type < ApplicationRecord
    has_and_belongs_to_many :pokemon_cards

    validates :name, presence: true, uniqueness: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    before_action :load_pokemon_card, only: [:create, :update, :destroy]
    before_action :validate_quantity, only: [:create, :update]
    before_action :load_cart_item, only: [:create, :update, :destroy]

    def index
        @pokemon_cards = PokemonCard.where(id: @cart.pluck("id"))
        @subtotal = @cart.sum { |item| item["quantity"] * @pokemon_cards.find(item["id"]).price }
    end

    def create
        if @cart_item
            temp_quantity = @cart_item["quantity"] + @quantity
            return redirect_to root_path unless temp_quantity <= @pokemon_card.stock_quantity
            @cart_item["quantity"] = temp_quantity
        else
            @cart.unshift({ "id" => @pokemon_card.id, "quantity" => @quantity })
        end

        redirect_to cart_index_path
    end

    def update
        return redirect_to root_path unless @cart_item

        @cart_item["quantity"] = @quantity

        redirect_to cart_index_path
    end

    def destroy
        @cart.delete(@cart_item) if @cart_item

        redirect_to cart_index_path
    end

    private

    def load_pokemon_card
        @pokemon_card = PokemonCard.find_by(id: params[:id])
        redirect_to root_path unless @pokemon_card
    end

    def validate_quantity
        @quantity = params[:quantity].to_i
        redirect_to root_path unless @quantity.positive? && @quantity <= @pokemon_card.stock_quantity
    end

    def load_cart_item
        @cart_item = @cart.find { |item| item["id"] == @pokemon_card.id }
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
    def show
        @type = Type.find(params[:id])
        @pokemon_cards = @type.pokemon_cards.where("stock_quantity > 0")

        if params[:filter].present?
            case params[:filter]
            when "new"
                @pokemon_cards = @pokemon_cards.where("created_at >= ?", 3.days.ago)
            when "recently_updated"
                @pokemon_cards = @pokemon_cards.where("updated_at >= ? AND created_at < ?", 3.days.ago, 3.days.ago)
            end
        end

        @pokemon_cards = @pokemon_cards.page(params[:page]).per(15)
    rescue ActiveRecord::RecordNotFound
        render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pokemon_cards_helper.rb
module PokemonCardsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/cart/index.html.erb
<h1 class="text-center mb-4">Your Cart</h1>

<% if @cart.any? %>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Card Details</th>
              <th scope="col" class="text-end">Price</th>
            </tr>
          </thead>
          <tbody>
            <% @cart.each do |item| %>
              <% pokemon_card = @pokemon_cards.find(item["id"]) %>
              <tr>
                <td>
                  <div class="d-flex align-items-start gap-3">
                    <%= image_tag pokemon_card.image, class: "img-fluid", style: "max-width: 100px;", alt: pokemon_card.name %>

                    <div>
                      <%= link_to pokemon_card_path(pokemon_card) do %>
                        <p><b><%= pokemon_card.name.capitalize %></b></p>
                      <% end %>

                      <%= form_tag(cart_path(item["id"]), method: :put, class: "mb-3", style: "width: 154.5px;") do %>
                        <div class="input-group flex-nowrap">
                          <%= number_field_tag(:quantity, item["quantity"], min: 1, max: pokemon_card.stock_quantity, class: "form-control", id: nil) %>
                          <button class="btn btn-primary">Update</button>
                        </div>
                      <% end %>

                      <%= button_to "Remove", cart_path(item["id"]), class: "btn btn-danger w-100", method: :delete, style: "width: 154.5px;" %>
                    </div>
                  </div>
                </td>
                <td class="text-end">$<%= '%.2f' % (pokemon_card.price) %></td>
              </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
              <td colspan="2" class="text-end">Subtotal (<%= @total_quantity %> item<%= "s" if @total_quantity > 1 %>): <b>$<%= '%.2f' % @subtotal %></b></td>
            </tr>
            <tr>
              <td colspan="2" class="text-end">
                <%= link_to "Proceed to Checkout", new_order_path, class: "btn btn-warning" %>
              </td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    Your cart is empty.
  </div>
<% end %>

app/views/types/show.html.erb
<h1 class="text-center mb-2"><%= @type.name.capitalize %> Pokemon Cards</h1>

<%= render partial: 'shared/pokemon_card_filter' %>

<% if @pokemon_cards.any? %>
  <div class="row justify-content-center gy-4">
    <% @pokemon_cards.each do |pokemon_card| %>
      <%= render partial: 'shared/pokemon_card', locals: { pokemon_card: pokemon_card } %>
    <% end %>
  </div>

  <div class="row mt-4">
    <%= paginate @pokemon_cards, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm justify-content-center", nav_class: "d-inline-b" %>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    No Pokemon Cards found.
  </div>
<% end %>