config/routes.rb
Rails.application.routes.draw do
  root 'pokemon_cards#index'
  resources :pokemon_cards, only: [:index, :show]
  resources :types, only: [:show]

  resources :search, only: [:index]
  resources :abouts, only: [:index]
  resources :contacts, only: [:index]

  resources :cart, only: [:index, :create, :update, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :customers
  scope '/customers' do
    resources :orders, only: [:index, :show, :new, :create] do
      get 'edit_shipping_address', on: :collection
      post 'update_shipping_address', on: :collection
    end
  end

  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    belongs_to :province

    has_many :order_details

    validates :customer_id, presence: true
    validates :province_id, presence: true
    validates :address, presence: true

    def total_quantity
        order_details.sum { |item| item.quantity }
    end

    def subtotal
        order_details.sum { |item| item.quantity * item.price }
    end

    def tax_history
        province.tax_histories.where("created_at <= ?", created_at).order(created_at: :desc).first
    end

    def pst
        subtotal * (tax_history&.pst || 0) / 100
    end

    def gst
        subtotal * (tax_history&.gst || 0) / 100
    end

    def hst
        subtotal * (tax_history&.hst || 0) / 100
    end

    def total
        subtotal + pst + gst + hst
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_customer!
    before_action :validate_cart, only: [:new, :edit_shipping_address, :update_shipping_address, :create]
    before_action :validate_shipping_address, only: [:new, :create]

    def index
        @orders = current_customer.orders
    end

    def show
        @order = current_customer.orders.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
    end

    def new
        @pokemon_cards = PokemonCard.where(id: @cart.pluck("id"))

        @subtotal = @cart.sum { |item| item["quantity"] * @pokemon_cards.find(item["id"]).price }

        @tax_history = current_customer.province.tax_histories.order(created_at: :desc).first

        @pst = @subtotal * (@tax_history&.pst || 0) / 100
        @gst = @subtotal * (@tax_history&.gst || 0) / 100
        @hst = @subtotal * (@tax_history&.hst || 0) / 100

        @total = @subtotal + @pst + @gst + @hst
    end

    def edit_shipping_address
        @address = session.delete(:address) || current_customer.address
        @province_id = session.delete(:province_id) || current_customer.province_id
    end

    def update_shipping_address
        flash[:errors] = []
        session[:address] = params[:address] || ""
        session[:province_id] = params[:province_id] || ""

        if session[:address].empty?
            flash[:errors] << "Address can't be blank"
        end

        if session[:province_id].empty?
            flash[:errors] << "Province can't be blank"
        else
            begin
                Province.find(session[:province_id])
            rescue ActiveRecord::RecordNotFound
                flash[:errors] << "Province is invalid"
            end
        end

        return redirect_to edit_shipping_address_orders_path if flash[:errors].present?

        current_customer.address = session[:address]
        current_customer.province_id = session[:province_id]
        current_customer.save

        redirect_to new_order_path
    end

    def create
        begin
            ActiveRecord::Base.transaction do
                new_order = current_customer.orders.create(
                    address: current_customer.address,
                    province_id: current_customer.province_id
                )

                pokemon_cards_to_save = []

                @cart.each do |item|
                    pokemon_card = PokemonCard.find(item["id"])

                    pokemon_card.stock_quantity -= item["quantity"]
                    pokemon_cards_to_save << pokemon_card

                    new_order.order_details.create(
                        pokemon_card_id: pokemon_card.id,
                        quantity: item["quantity"],
                        price: pokemon_card.price
                    )
                end

                pokemon_cards_to_save.each(&:save!)

                session[:cart] = []
                redirect_to order_path(new_order)
            end
        rescue ActiveRecord::RecordInvalid => e
            flash[:errors] = []

            @cart.each do |item|
                pokemon_card = PokemonCard.find(item["id"])

                if item["quantity"] > pokemon_card.stock_quantity
                    flash[:errors] << "Quantity is invalid for #{pokemon_card.name.capitalize}"
                end
            end

            redirect_to new_order_path
        end
    end

    private

    def validate_cart
        redirect_to cart_index_path if @cart.empty?
    end

    def validate_shipping_address
        redirect_to edit_shipping_address_orders_path if current_customer.address.empty? || current_customer.province_id.nil?
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit_shipping_address.html.erb
<h1 class="text-center mb-4">Checkout</h1>

<div class="row justify-content-center">
  <div class="col-md-3">
    <h3>Shipping Address</h3>

    <%= form_with(url: update_shipping_address_orders_path, method: :post) do %>
      <%= render partial: "shared/error_messages", locals: { flash: flash } %>

      <div class="mb-3">
        <%= label_tag(:address, class: "form-label") do %>
          Address<span class="text-danger">*</span>
        <% end %>
        <%= text_field_tag(:address, @address, class: "form-control") %>
      </div>

      <div class="mb-3">
        <%= label_tag(:province_id, class: "form-label") do %>
          Province<span class="text-danger">*</span>
        <% end %>
        <%= select_tag(:province_id, options_from_collection_for_select(Province.all, :id, :name, @province_id), include_blank: "No Province", class: "form-select") %>
      </div>

      <div class="mb-3 text-center">
        <button class="btn btn-primary">Save</button>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/index.html.erb
<h1 class="text-center mb-4">Your Orders</h1>

<% if @orders.any? %>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Order #</th>
              <th>Order Date</th>
              <th>Order Total</th>
              <th>Order Details</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr class="align-middle">
                <td><%= order.id %></td>
                <td><%= order.created_at.strftime("%B %d, %Y") %></td>
                <td>$<%= '%.2f' % order.total %></td>
                <td><%= link_to 'View', order_path(order), class: "btn btn-outline-primary" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    You have no orders.
  </div>
<% end %>

app/views/orders/new.html.erb
<h1 class="text-center mb-4">Checkout</h1>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h3>Shipping Address</h3>

    <div class="table-responsive">
      <table class="table">
        <tbody>
          <tr>
            <td>Address: <%= current_customer.address %></td>
          </tr>
          <tr>
            <td>Province: <%= current_customer.province.name %></td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td class="text-end">
              <%= link_to "Change", edit_shipping_address_orders_path, class: "btn btn-primary" %>
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h3>Order Summary</h3>

    <%= render partial: "shared/error_messages", locals: { flash: flash } %>

    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Card Details</th>
            <th scope="col" class="text-end">Price</th>
          </tr>
        </thead>
        <tbody>
          <% @cart.each do |item| %>
            <% pokemon_card = @pokemon_cards.find(item["id"]) %>
            <tr>
              <td>
                <div class="d-flex align-items-start gap-3">
                  <%= image_tag pokemon_card.image, class: "img-fluid", style: "max-width: 100px;", alt: pokemon_card.name %>

                  <div>
                    <%= link_to pokemon_card_path(pokemon_card) do %>
                      <p><b><%= pokemon_card.name.capitalize %></b></p>
                    <% end %>

                    <p>Quantity: <b><%= item["quantity"] %></b></p>
                  </div>
                </div>
              </td>
              <td class="text-end">$<%= '%.2f' % (pokemon_card.price) %></td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2" class="text-end">Subtotal (<%= @total_quantity %> item<%= "s" if @total_quantity > 1 %>): $<%= '%.2f' % @subtotal %></td>
          </tr>
          <tr>
            <td colspan="2" class="text-end">PST (<%= @tax_history&.pst || 0.0 %>%): $<%= '%.2f' % @pst %></td>
          </tr>
          <tr>
            <td colspan="2" class="text-end">GST (<%= @tax_history&.gst || 0.0 %>%): $<%= '%.2f' % @gst %></td>
          </tr>
          <tr>
            <td colspan="2" class="text-end">HST (<%= @tax_history&.hst || 0.0 %>%): $<%= '%.2f' % @hst %></td>
          </tr>
          <tr>
            <td colspan="2" class="text-end text-danger"><b>Order Total: $<%= '%.2f' % @total %></b></td>
          </tr>
          <tr>
            <td colspan="2" class="text-end">
              <%= button_to "Place your order", orders_path, class: "btn btn-warning", method: :post %>
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<h1 class="text-center mb-4">Order Details #<%= @order.id %></h1>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h3>Shipping Address</h3>

    <div class="table-responsive">
      <table class="table">
        <tbody>
          <tr>
            <td>Address: <%= @order.address %></td>
          </tr>
          <tr>
            <td>Province: <%= @order.province.name %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h3>Order Summary</h3>

    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Card Details</th>
            <th scope="col" class="text-end">Price</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |item| %>
            <tr>
              <td>
                <div class="d-flex align-items-start gap-3">
                  <%= image_tag item.pokemon_card.image, class: "img-fluid", style: "max-width: 100px;", alt: item.pokemon_card.name %>

                  <div>
                    <%= link_to pokemon_card_path(item.pokemon_card) do %>
                      <p><b><%= item.pokemon_card.name.capitalize %></b></p>
                    <% end %>

                    <p>Quantity: <b><%= item.quantity %></b></p>
                  </div>
                </div>
              </td>
              <td class="text-end">$<%= '%.2f' % (item.price) %></td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2" class="text-end">Subtotal (<%= @order.total_quantity %> item<%= "s" if @order.total_quantity > 1 %>): $<%= '%.2f' % @order.subtotal %></td>
          </tr>
          <tr>
            <td colspan="2" class="text-end">PST (<%= @order.tax_history&.pst || 0.0 %>%): $<%= '%.2f' % @order.pst %></td>
          </tr>
          <tr>
            <td colspan="2" class="text-end">GST (<%= @order.tax_history&.gst || 0.0 %>%): $<%= '%.2f' % @order.gst %></td>
          </tr>
          <tr>
            <td colspan="2" class="text-end">HST (<%= @order.tax_history&.hst || 0.0 %>%): $<%= '%.2f' % @order.hst %></td>
          </tr>
          <tr>
            <td colspan="2" class="text-end text-danger"><b>Order Total: $<%= '%.2f' % @order.total %></b></td>
          </tr>
          <tr>
            <td colspan="2" class="text-end">Ordered on <%= @order.created_at.strftime("%B %d, %Y") %></td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>