config/routes.rb
Rails.application.routes.draw do
  root 'pokemon_cards#index'
  resources :pokemon_cards, only: [:index, :show]
  resources :types, only: [:show]

  resources :search, only: [:index]
  resources :abouts, only: [:index]
  resources :contacts, only: [:index]

  resources :cart, only: [:index, :create, :update, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :customers
  scope '/customers' do
    resources :orders, only: [:index, :show, :new, :create] do
      get 'edit_shipping_address', on: :collection
      post 'update_shipping_address', on: :collection
    end
  end

  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/pokemon_card.rb
class PokemonCard < ApplicationRecord
    has_and_belongs_to_many :types
    has_many :price_histories
    has_many :order_details

    has_one_attached :image

    validates :name, presence: true
    validates :stock_quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }

    validate :image_presence
    validate :types_presence

    def new?
        created_at >= 3.days.ago
    end

    def recently_updated?
        updated_at >= 3.days.ago
    end

    def price
        price_histories.order(created_at: :desc).first.price
    end

    private

    def image_presence
        errors.add(:image, "must be attached") unless image.attached?
    end

    def types_presence
        errors.add(:types, "must be present") if types.empty?
    end
end

app/controllers/pokemon_cards_controller.rb
class PokemonCardsController < ApplicationController
    def index
        @pokemon_cards = PokemonCard.where("stock_quantity > 0")

        if params[:filter].present?
            case params[:filter]
            when "new"
                @pokemon_cards = @pokemon_cards.where("created_at >= ?", 3.days.ago)
            when "recently_updated"
                @pokemon_cards = @pokemon_cards.where("updated_at >= ? AND created_at < ?", 3.days.ago, 3.days.ago)
            end
        end

        @pokemon_cards = @pokemon_cards.page(params[:page]).per(15)
    end

    def show
        @pokemon_card = PokemonCard.find(params[:id])
        render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false unless @pokemon_card.stock_quantity > 0
    rescue ActiveRecord::RecordNotFound
        render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
    end
end

app/helpers/pokemon_cards_helper.rb
module PokemonCardsHelper
end

app/views/pokemon_cards/index.html.erb
<h1 class="text-center mb-2">Pokemon Cards</h1>

<%= render partial: 'shared/pokemon_card_filter' %>

<% if @pokemon_cards.any? %>
  <div class="row justify-content-center gy-4">
    <% @pokemon_cards.each do |pokemon_card| %>
      <%= render partial: 'shared/pokemon_card', locals: { pokemon_card: pokemon_card } %>
    <% end %>
  </div>

  <div class="row mt-4">
    <%= paginate @pokemon_cards, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm justify-content-center", nav_class: "d-inline-b" %>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    No Pokemon Cards found.
  </div>
<% end %>

app/views/pokemon_cards/show.html.erb
<h1 class="text-center mb-4"><%= @pokemon_card.name.capitalize %></h1>

<div class="row justify-content-center align-items-center gap-4">
  <div class="col-md-4 text-center">
    <% if @pokemon_card.new? %>
      <span class="badge bg-primary rounded-0 rounded-top w-50">New</span>
    <% elsif @pokemon_card.recently_updated? %>
      <span class="badge bg-warning rounded-0 rounded-top w-50">Updated</span>
    <% end %>

    <%= image_tag @pokemon_card.image, class: 'w-75', alt: @pokemon_card.name %>
  </div>

  <div class="col-md-4 d-flex justify-content-center">
    <div>
      <p>
        <b>Type:</b>
        <%= @pokemon_card.types.map { |type| link_to(type.name, type_path(type)) }.join(', ').html_safe %>
      </p>
      <p><b>Description:</b> <%= @pokemon_card.description.present? ? @pokemon_card.description : "N/A" %></p>
      <p><b>Price:</b> $<%= '%.2f' % @pokemon_card.price %></p>
      <p><b>Stock Quantity:</b> <%= @pokemon_card.stock_quantity %></p>

      <% if @pokemon_card.stock_quantity > 0 %>
        <%= form_tag(cart_index_path, method: :post, class: "mb-3", style: "width: 214.516px;") do %>
          <%= hidden_field_tag(:id, @pokemon_card.id) %>
          <div class="input-group flex-nowrap">
            <%= number_field_tag(:quantity, 1, min: 1, max: @pokemon_card.stock_quantity, class: "form-control") %>
            <button class="btn btn-primary">Add to Cart</button>
          </div>
        <% end %>
      <% else %>
        <p class="text-danger"><b>Out of stock</b></p>
      <% end %>
    </div>
  </div>
</div>