config/routes.rb
Rails.application.routes.draw do
  root 'pokemon_cards#index'
  resources :pokemon_cards, only: [:index, :show]
  resources :types, only: [:show]

  resources :search, only: [:index]
  resources :abouts, only: [:index]
  resources :contacts, only: [:index]

  resources :cart, only: [:index, :create, :update, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :customers
  scope '/customers' do
    resources :orders, only: [:index, :show, :new, :create] do
      get 'edit_shipping_address', on: :collection
      post 'update_shipping_address', on: :collection
    end
  end

  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/about.rb
class About < ApplicationRecord
    validates :content, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :title, presence: true
    validates :email, presence: true, format: { with: /\A\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+\z/, message: "is invalid" }
    validates :phone, presence: true, format: { with: /\A[\+]?\d{0,3}[(]?\d{3}[)]?[-\s\.]?\d{3}[-\s\.]?\d{4}\z/, message: "is invalid" }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province, optional: true

  has_many :orders

  validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9_-]{3,15}\z/, message: "should be 3 to 15 characters long and can only contain letters, digits, underscores, and hyphens" }
  validates :email, format: { with: /\A\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+\z/, message: "is invalid" }
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    belongs_to :province

    has_many :order_details

    validates :customer_id, presence: true
    validates :province_id, presence: true
    validates :address, presence: true

    def total_quantity
        order_details.sum { |item| item.quantity }
    end

    def subtotal
        order_details.sum { |item| item.quantity * item.price }
    end

    def tax_history
        province.tax_histories.where("created_at <= ?", created_at).order(created_at: :desc).first
    end

    def pst
        subtotal * (tax_history&.pst || 0) / 100
    end

    def gst
        subtotal * (tax_history&.gst || 0) / 100
    end

    def hst
        subtotal * (tax_history&.hst || 0) / 100
    end

    def total
        subtotal + pst + gst + hst
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :pokemon_card

    validates :order_id, presence: true
    validates :pokemon_card_id, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0.01 }
    validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/pokemon_card.rb
class PokemonCard < ApplicationRecord
    has_and_belongs_to_many :types
    has_many :price_histories
    has_many :order_details

    has_one_attached :image

    validates :name, presence: true
    validates :stock_quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }

    validate :image_presence
    validate :types_presence

    def new?
        created_at >= 3.days.ago
    end

    def recently_updated?
        updated_at >= 3.days.ago
    end

    def price
        price_histories.order(created_at: :desc).first.price
    end

    private

    def image_presence
        errors.add(:image, "must be attached") unless image.attached?
    end

    def types_presence
        errors.add(:types, "must be present") if types.empty?
    end
end

app/models/price_history.rb
class PriceHistory < ApplicationRecord
    belongs_to :pokemon_card

    validates :pokemon_card_id, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0.01 }
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :tax_histories
    has_many :customers
    has_many :orders

    validates :name, presence: true, uniqueness: true
end

app/models/tax_history.rb
class TaxHistory < ApplicationRecord
    belongs_to :province

    validates :province_id, presence: true
    validates :pst, :gst, :hst, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }, allow_nil: true
    validate :at_least_one_tax_present_and_positive

    private

    def at_least_one_tax_present_and_positive
        if [pst, gst, hst].all?(&:blank?)
            errors.add(:base, "at least one tax must be present")
        elsif [pst, gst, hst].none? { |tax| tax.to_f > 0 }
            errors.add(:base, "at least one tax must be greater than 0")
        end
    end
end

app/models/type.rb
class Type < ApplicationRecord
    has_and_belongs_to_many :pokemon_cards

    validates :name, presence: true, uniqueness: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    before_action :load_pokemon_card, only: [:create, :update, :destroy]
    before_action :validate_quantity, only: [:create, :update]
    before_action :load_cart_item, only: [:create, :update, :destroy]

    def index
        @pokemon_cards = PokemonCard.where(id: @cart.pluck("id"))
        @subtotal = @cart.sum { |item| item["quantity"] * @pokemon_cards.find(item["id"]).price }
    end

    def create
        if @cart_item
            temp_quantity = @cart_item["quantity"] + @quantity
            return redirect_to root_path unless temp_quantity <= @pokemon_card.stock_quantity
            @cart_item["quantity"] = temp_quantity
        else
            @cart.unshift({ "id" => @pokemon_card.id, "quantity" => @quantity })
        end

        redirect_to cart_index_path
    end

    def update
        return redirect_to root_path unless @cart_item

        @cart_item["quantity"] = @quantity

        redirect_to cart_index_path
    end

    def destroy
        @cart.delete(@cart_item) if @cart_item

        redirect_to cart_index_path
    end

    private

    def load_pokemon_card
        @pokemon_card = PokemonCard.find_by(id: params[:id])
        redirect_to root_path unless @pokemon_card
    end

    def validate_quantity
        @quantity = params[:quantity].to_i
        redirect_to root_path unless @quantity.positive? && @quantity <= @pokemon_card.stock_quantity
    end

    def load_cart_item
        @cart_item = @cart.find { |item| item["id"] == @pokemon_card.id }
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PokeMart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to "PokeMart", root_path, class: "navbar-brand" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li>
              <%= link_to "Cards", pokemon_cards_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Types</a>
              <div class="dropdown-menu">
                <% Type.all.each do |type| %>
                  <%= link_to type.name.capitalize, type_path(type), class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
            <li>
              <%= link_to "About", abouts_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "Contact", contacts_path, class: "nav-link" %>
            </li>
          </ul>

          <%= form_with(url: search_index_path, method: "get", class: "form-inline flex-grow-1") do %>
            <div class="input-group flex-nowrap">
              <%= select_tag(:type, options_from_collection_for_select(Type.all, :id, :name, params[:type]), include_blank: "All Types", class: "form-select rounded-0 rounded-start flex-grow-0 w-auto") %>

              <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "Search for Pokemon Card", aria: { label: "Search" }) %>

              <button class="btn btn-success">Search</button>
            </div>
          <% end %>

          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= customer_signed_in? ? current_customer.username : "Menu" %>
              </a>
              <div class="dropdown-menu">
                <% if customer_signed_in? %>
                  <%= link_to "Your Orders", orders_path, class: "dropdown-item" %>
                  <%= link_to "Edit Profile", edit_customer_registration_path, class: "dropdown-item" %>
                  <%= button_to "Sign Out", destroy_customer_session_path, class: "dropdown-item", method: :delete %>
                <% else %>
                  <%= link_to "Sign Up", new_customer_registration_path, class: "dropdown-item" %>
                  <%= link_to "Sign In", new_customer_session_path, class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
            <li>
              <%= link_to cart_index_path, class: "nav-link" do %>
                Cart <span class="badge bg-secondary"><%= @total_quantity %></span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-3">
          <% if notice %>
            <p class="alert alert-info"><%= notice %></p>
          <% end %>

          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
        </div>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if flash[:errors].present? %>
  <div id="error_explanation" class="alert alert-danger" data-turbo-cache="false">
    <b><%= flash[:errors].count %> error<%= "s" if flash[:errors].count > 1 %> prohibited this from being saved:</b>
    <ul>
      <% flash[:errors].each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_pokemon_card.html.erb
<div class="col-md-4">
  <div class="d-flex flex-column align-items-center">
    <% if pokemon_card.new? %>
      <span class="badge bg-primary rounded-0 rounded-top w-50">New</span>
    <% elsif pokemon_card.recently_updated? %>
      <span class="badge bg-warning rounded-0 rounded-top w-50">Updated</span>
    <% end %>

    <%= image_tag pokemon_card.image, class: 'w-75', alt: pokemon_card.name %>

    <%= link_to pokemon_card_path(pokemon_card) do %>
      <h3 class="text-center"><%= pokemon_card.name.capitalize %></h3>
    <% end %>

    <p>Price: $<%= '%.2f' % pokemon_card.price %></p>
  </div>
</div>

app/views/shared/_pokemon_card_filter.html.erb
<%= form_with(method: "get", class: "mb-4") do %>
  <div class="row justify-content-center">
    <div class="col-md-2">
      <%= label_tag(:filter, "Filter by:", class: "form-label") %>
      <%= select_tag(:filter, options_for_select([["No filter", ""], ["New", "new"], ["Recently Updated", "recently_updated"]], params[:filter]), onchange: "this.form.submit()", class: "form-select") %>
    </div>
  </div>
<% end %>